stages:
  process-all-datasets:
    cmd: >
      python ocmscripts/dataset.py
      data/external/2023-isb-multisite.csv
      data/external/2023-clb-multisite.csv
      data/external/2025-ksa-oral-cavity.csv
      --output-path=data/processed/dataset.csv
    deps:
      - uv.lock
      - ocmscripts/dataset.py
      - data/external/2023-isb-multisite.csv
      - data/external/2023-clb-multisite.csv
      - data/external/2025-ksa-oral-cavity.csv
    outs:
      - data/processed/dataset.csv

  process-data-ksa:
    cmd: >
      python ocmscripts/dataset.py
      data/external/2025-ksa-oral-cavity.csv
      --output-path=data/processed/dataset_ksa.csv
    deps:
      - uv.lock
      - ocmscripts/dataset.py
      - data/external/2025-ksa-oral-cavity.csv
    outs:
      - data/processed/dataset_ksa.csv

  process-data-isb-clb:
    cmd: >
      python ocmscripts/dataset.py
      data/external/2023-isb-multisite.csv
      data/external/2023-clb-multisite.csv
      --output-path=data/processed/dataset_isb_clb.csv
    deps:
      - uv.lock
      - ocmscripts/dataset.py
      - data/external/2023-isb-multisite.csv
      - data/external/2023-clb-multisite.csv
    outs:
      - data/processed/dataset_isb_clb.csv

  data-plots-ipsi:
    cmd: >
      python ocmscripts/plots/data_plots_ipsi.py
    deps:
      - uv.lock
      - data/processed/dataset_ksa.csv
      - data/processed/dataset_isb_clb.csv
      - ocmscripts/plots/data_plots_ipsi.py
    outs:
      - reports/figures/data_ksa_vs_isb_clb_by_tstage.pdf

  data-plots-contra:
    cmd: >
      python ocmscripts/plots/data_plots_contra.py
    deps:
      - uv.lock
      - data/processed/dataset.csv
      - ocmscripts/plots/data_plots_contra.py
    outs:
      - reports/figures/contra_by_t_and_midext.pdf

  data-plots-contra-ipsi:
    cmd: >
      python ocmscripts/plots/data_plots_contra_ipsi.py
    deps:
      - uv.lock
      - data/processed/dataset.csv
      - ocmscripts/plots/data_plots_contra_ipsi.py
    outs:
      - reports/figures/contra_by_inv_midext.pdf

  integration:
    foreach: ${models}
    do:
      cmd: >
        lyscripts integrate
        --configs models/configs/graphs/${item}.ly.yaml
        --configs models/configs/max_llh.ly.yaml
        --configs models/configs/integration.ly.yaml
        --data.source data/processed/dataset.csv
        --sampling.storage-file models/samples/${item}_integration.hdf5
        --sampling.history-file models/histories/${item}_integration.csv
      deps:
        - uv.lock
        - data/processed/dataset.csv
        - models/configs/graphs/${item}.ly.yaml
      params:
        - models/configs/graphs/${item}.ly.yaml:
        - models/configs/max_llh.ly.yaml:
        - models/configs/integration.ly.yaml:
      outs:
        - models/histories/${item}_integration.csv
        - models/samples/${item}_integration.hdf5

  evaluate:
    foreach: ${models}
    do:
      cmd: >
        model_name=${item} lyscripts compute evidence
        --configs models/configs/integration.ly.yaml
        --data.source data/processed/dataset.csv
        --sampling.storage-file models/samples/${item}_integration.hdf5
        --sampling.history-file models/histories/${item}_integration.csv
        --plots reports/plots/plots_${item}
        --metrics reports/metrics/metrics_${item}.json
      deps:
        - uv.lock
        - data/processed/dataset.csv
        - models/samples/${item}_integration.hdf5
      params:
        - models/configs/integration.ly.yaml:
      outs:
        - reports/metrics/metrics_${item}.json
        - reports/plots/plots_${item}


  prevalences-base:
    cmd: >
      lyscripts compute prevalences
      --configs models/configs/graphs/base.ly.yaml
      --configs models/configs/integration.ly.yaml
      --configs models/configs/scenarios/base_scenarios.ly.yaml
      --prevalences.file models/prevalences/base_integration.hdf5
      --data.source data/processed/dataset.csv
      --sampling.storage-file models/samples/base_integration.hdf5
      --sampling.history-file models/histories/base_integration.csv
    deps:
      - uv.lock
      - models/samples/base_integration.hdf5
      - data/processed/dataset.csv
    params:
      - models/configs/graphs/base.ly.yaml:
      - models/configs/integration.ly.yaml:
      - models/configs/scenarios/base_scenarios.ly.yaml:
    outs:
      - models/prevalences/base_integration.hdf5
  
  plot-prevalences-base:
    cmd: >
      python ocmscripts/plots/base_prevalences.py
    deps:
      - uv.lock
      - models/prevalences/base_integration.hdf5
      - ocmscripts/plots/base_prevalences.py
    outs:
      - reports/figures/base_prevalences_LNLII.pdf
      - reports/figures/base_prevalences_LNLIII.pdf
      - reports/figures/base_prevalences_LNLIV.pdf

  prevalences-winning:
    matrix:
      model: [base, base+II_I+III_V]
      scenario: [winning_scenarios]
    cmd: >
      lyscripts compute prevalences
      --configs models/configs/graphs/${item.model}.ly.yaml
      --configs models/configs/integration.ly.yaml
      --configs models/configs/scenarios/${item.scenario}.ly.yaml
      --prevalences.file models/prevalences/${item.model}_${item.scenario}_integration.hdf5
      --data.source data/processed/dataset.csv
      --sampling.storage-file models/samples/${item.model}_integration.hdf5
      --sampling.history-file models/histories/${item.model}_integration.csv
    deps:
      - uv.lock
      - models/samples/${item.model}_integration.hdf5
      - data/processed/dataset.csv
    params:
      - models/configs/graphs/${item.model}.ly.yaml:
      - models/configs/integration.ly.yaml:
      - models/configs/scenarios/${item.scenario}.ly.yaml:
    outs:
      - models/prevalences/${item.model}_${item.scenario}_integration.hdf5

  plot-prevalences-winning:
    cmd: > 
      python ocmscripts/plots/winning_prevalences.py
    deps:
      - uv.lock
      - models/prevalences/base_winning_scenarios_integration.hdf5
      - models/prevalences/base+II_I+III_V_winning_scenarios_integration.hdf5
      - ocmscripts/plots/winning_prevalences.py
    outs:
      - reports/figures/winning_vs_base_I.pdf
      - reports/figures/winning_vs_base_V.pdf

  
  sample-midline:
    cmd: >
      lyscripts sample  
      --configs models/configs/graphs/midline+II_I+III_V.ly.yaml
      --configs models/configs/max_llh.ly.yaml
      --configs models/configs/sampling.ly.yaml
      --data.source data/processed/dataset.csv
    deps:
      - uv.lock
      - data/processed/dataset.csv
      - models/configs/graphs/midline+II_I+III_V.ly.yaml
    params:
      - models/configs/graphs/midline+II_I+III_V.ly.yaml:
      - models/configs/max_llh.ly.yaml:
      - models/configs/integration.ly.yaml:
    outs:
      - models/histories/midline_II_I_III_V.csv
      - models/samples/midline_II_I_III_V.hdf5

  
  prevalences-midline-contra:
    cmd: >
      lyscripts compute prevalences
      --configs models/configs/graphs/midline+II_I+III_V.ly.yaml
      --configs models/configs/sampling.ly.yaml
      --configs models/configs/scenarios/midline_scenarios_contra.ly.yaml
      --prevalences.file models/prevalences/midline_II_I_III_V.hdf5
      --data.source data/processed/dataset.csv
      --sampling.storage-file models/samples/midline_II_I_III_V.hdf5
      --sampling.history-file models/histories/midline_II_I_III_V.csv
    deps:
      - uv.lock
      - models/samples/midline_II_I_III_V.hdf5
      - data/processed/dataset.csv
    params:
      - models/configs/graphs/midline+II_I+III_V.ly.yaml:
      - models/configs/integration.ly.yaml:
      - models/configs/scenarios/midline_scenarios_contra.ly.yaml:
    outs:
      - models/prevalences/midline_II_I_III_V.hdf5
  
  plot-midline-contra-prevalences:
    cmd: >
      python ocmscripts/plots/midline_contra_prevalences.py
    deps:
      - uv.lock
      - models/prevalences/midline_II_I_III_V.hdf5
      - ocmscripts/plots/midline_contra_prevalences.py
    outs:
      - reports/figures/midline_contra_prevalences.pdf


  prevalences-midline-upstream:
    cmd: >
      lyscripts compute prevalences
      --configs models/configs/graphs/midline+II_I+III_V.ly.yaml
      --configs models/configs/sampling.ly.yaml
      --configs models/configs/scenarios/midline_scenarios_upstream.ly.yaml
      --prevalences.file models/prevalences/midline_II_I_III_V_upstream.hdf5
      --data.source data/processed/dataset.csv
      --sampling.storage-file models/samples/midline_II_I_III_V.hdf5
      --sampling.history-file models/histories/midline_II_I_III_V.csv
    deps:
      - uv.lock
      - models/samples/midline_II_I_III_V.hdf5
      - data/processed/dataset.csv
    params:
      - models/configs/graphs/midline+II_I+III_V.ly.yaml:
      - models/configs/integration.ly.yaml:
      - models/configs/scenarios/midline_scenarios_upstream.ly.yaml:
    outs:
      - models/prevalences/midline_II_I_III_V_upstream.hdf5

  plot-midline-upstream-prevalences:
    cmd: >
      python ocmscripts/plots/midline_upstream_prevalences.py
    deps:
      - uv.lock
      - models/prevalences/midline_II_I_III_V_upstream.hdf5
      - ocmscripts/plots/midline_upstream_prevalences.py
    outs:
      - reports/figures/midline_upstream_prevalences_LNLI.pdf
      - reports/figures/midline_upstream_prevalences_LNLIII.pdf


  risks-ipsi:
    cmd: >
      lyscripts compute risks
      --configs models/configs/sampling.ly.yaml
      --configs models/configs/graphs/midline+II_I+III_V.ly.yaml
      --configs models/configs/scenarios/midline_scenarios_risk_ipsi.ly.yaml
      --risks.file models/risks/midline_risks_ipsi.hdf5
    deps:
      - uv.lock
      - models/samples/midline_II_I_III_V.hdf5
    params:
      - models/configs/sampling.ly.yaml:
      - models/configs/graphs/midline+II_I+III_V.ly.yaml:
      - models/configs/scenarios/midline_scenarios_risk_ipsi.ly.yaml:
    outs:
      - models/risks/midline_risks_ipsi.hdf5
  
  plot-risks-ipsi:
    cmd: >
      python ocmscripts/plots/risks_ipsi.py
    deps:
      - uv.lock
      - models/risks/midline_risks_ipsi.hdf5
      - ocmscripts/plots/risks_ipsi.py
    outs:
      - reports/figures/risks_ipsi.pdf


  risks contra:
    cmd: >
      lyscripts compute risks
      --configs models/configs/sampling.ly.yaml
      --configs models/configs/graphs/midline+II_I+III_V.ly.yaml
      --configs models/configs/scenarios/midline_scenarios_risk_contra.ly.yaml
      --risks.file models/risks/midline_risks_contra.hdf5
    deps:
      - uv.lock
      - models/samples/midline_II_I_III_V.hdf5
    params:
      - models/configs/sampling.ly.yaml:
      - models/configs/graphs/midline+II_I+III_V.ly.yaml:
      - models/configs/scenarios/midline_scenarios_risk_contra.ly.yaml:
    outs:
      - models/risks/midline_risks_contra.hdf5

  
  plot-risks-contra:
    cmd: >
      python ocmscripts/plots/risks_contra.py
    deps:
      - uv.lock
      - models/risks/midline_risks_contra.hdf5
      - ocmscripts/plots/risks_contra.py
    outs:
      - reports/figures/risks_contra.pdf