version: 1

sampling:
  storage_file: models/samples/default_integration.hdf5
  history_file: models/histories/default_integration.csv
  dataset: mcmc
  seed: 42
  walkers_per_dim: 20
  check_interval: 50
  trust_factor: 50
  relative_thresh: 0.05
  thin_by: 10
  burnin_steps: 2500
  num_steps: 30
  inverse_temp: 1.0


schedule:
  method: power
  num: 64
  power: 5.0
  