version: 1

modalities:
  max_llh:
    spec: 1.0
    sens: 1.0
    kind: pathological

# LNL I
scenarios:
  - t_stages: [early]
    midext: false
    mode: HMM
    diagnosis:
      contra:
        max_llh: {I: true, II: true}
      ipsi:
        max_llh: {}
  - t_stages: [late]
    midext: false
    mode: HMM
    diagnosis:
      contra:
        max_llh: {I: true, II: true}
      ipsi:
        max_llh: {}

  - t_stages: [early]
    midext: true
    mode: HMM
    diagnosis:
      contra:
        max_llh: {I: true, II: true}
      ipsi:
        max_llh: {}
  - t_stages: [late]
    midext: true
    mode: HMM
    diagnosis:
      contra:
        max_llh: {I: true, II: true}
      ipsi:
        max_llh: {}


  - t_stages: [early]
    midext: false
    mode: HMM
    diagnosis:
      contra:
        max_llh: {I: true, II: false}
      ipsi:
        max_llh: {}
  - t_stages: [late]
    midext: false
    mode: HMM
    diagnosis:
      contra:
        max_llh: {I: true, II: false}
      ipsi:
        max_llh: {}

  - t_stages: [early]
    midext: true
    mode: HMM
    diagnosis:
      contra:
        max_llh: {I: true, II: false}
      ipsi:
        max_llh: {}
  - t_stages: [late]
    midext: true
    mode: HMM
    diagnosis:
      contra:
        max_llh: {I: true, II: false}
      ipsi:
        max_llh: {}




# LNL III
  - t_stages: [early]
    midext: false
    mode: HMM
    diagnosis:
      contra:
        max_llh: {II: true, III: true}
      ipsi:
        max_llh: {}
  - t_stages: [late]
    midext: false
    mode: HMM
    diagnosis:
      contra:
        max_llh: {II: true, III: true}
      ipsi:
        max_llh: {}

  - t_stages: [early]
    midext: true
    mode: HMM
    diagnosis:
      contra:
        max_llh: {II: true, III: true}
      ipsi:
        max_llh: {}
  - t_stages: [late]
    midext: true
    mode: HMM
    diagnosis:
      contra:
        max_llh: {II: true, III: true}
      ipsi:
        max_llh: {}

  - t_stages: [early]
    midext: false
    mode: HMM
    diagnosis:
      contra:
        max_llh: {II: false, III: true}
      ipsi:
        max_llh: {}
  - t_stages: [late]
    midext: false
    mode: HMM
    diagnosis:
      contra:
        max_llh: {II: false, III: true}
      ipsi:
        max_llh: {}

  - t_stages: [early]
    midext: true
    mode: HMM
    diagnosis:
      contra:
        max_llh: {II: false, III: true}
      ipsi:
        max_llh: {}
  - t_stages: [late]
    midext: true
    mode: HMM
    diagnosis:
      contra:
        max_llh: {II: false, III: true}
      ipsi:
        max_llh: {}


  