version: 1

modalities:
  max_llh:
    spec: 1.0
    sens: 1.0
    kind: pathological

scenarios:
  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          II: involved
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          II: involved
  
  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          II: involved
          III: involved
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          II: involved
          III: involved

  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          II: involved
          III: healthy
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          II: involved
          III: healthy


  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          III: involved
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          III: involved
  
  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          III: involved
          IV: involved
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          III: involved
          IV: involved
  
  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          III: involved
          IV: healthy
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          III: involved
          IV: healthy
  
  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          II: healthy
          III: involved
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          II: healthy
          III: involved



  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          IV: involved
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          IV: involved
  
  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          III: healthy
          IV: involved
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          III: healthy
          IV: involved

  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          II: healthy
          IV: involved
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        max_llh:
          II: healthy
          IV: involved